In [24]:
# NO . 4

In [25]:
# Bonus Question.

In [26]:
import numpy as np

In [27]:
# a) Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (Hint: create a 5x3 and 3x2 matrices
#    and peform matrix multiplication).

In [28]:
A = np.array([[1, 2, 3], [2, 3, 1], [2, 1, 3], [3, 1, 2] , [3, 2, 1]])
print(A)

[[1 2 3]
 [2 3 1]
 [2 1 3]
 [3 1 2]
 [3 2 1]]


In [29]:
B = np.array([[1, 2], [1, 3], [2, 3]])
print(B)

[[1 2]
 [1 3]
 [2 3]]


In [30]:

multiply= np.dot(A, B)
print(multiply)

[[ 9 17]
 [ 7 16]
 [ 9 16]
 [ 8 15]
 [ 7 15]]


In [31]:
# b) Create a 3x3 identity matrix

In [32]:
identity_A = np.eye(3)

print(identity_A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
# c) Create a vector with values ranging from 10 to 49).

In [34]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [35]:
# d) Create a null vector of size 10.

In [36]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [37]:
# e) Create a 3x3x3 array with random values

In [38]:
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.91913922 0.00602315 0.55910163]
  [0.6180313  0.77720757 0.46091874]
  [0.95283374 0.89644891 0.83060037]]

 [[0.00267715 0.10933084 0.70557515]
  [0.08534467 0.29645174 0.67352402]
  [0.56344663 0.18250377 0.88661724]]

 [[0.76330801 0.73794164 0.15563067]
  [0.66127096 0.42927778 0.25262584]
  [0.92112096 0.37202197 0.14774636]]]


In [39]:
# f) Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [40]:
A= np.array([[0,0,0,0,0],[1,0,0,0,0],[1,2,0,0,0],[1,2,3,0,0],[1,2,3,4,0]])
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


In [41]:
# g) Normalize a 5x5 random matrix

In [42]:
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print(normalized_matrix)

[[0.29377922 0.21173653 0.55635008 0.46604782 0.58008989]
 [0.42534672 0.84070806 0.77913233 0.19002322 0.64350357]
 [0.67987002 0.31052662 0.46211475 0.79925622 0.51384657]
 [0.5306472  0.71981543 1.         0.64553085 0.27767888]
 [0.66790344 0.29600493 0.09893067 0.         0.2511848 ]]


In [43]:
# h) How to get the dates of yesterday, today and tomorrow?

In [45]:
today = np.datetime64('today', 'D') # TODAY'S DATE

yesterday = today - np.timedelta64(1, 'D') # YESTERDAY'S DATE

tomorrow = today + np.timedelta64(1, 'D') # TOMORROWS DATE

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-12-12
Today: 2024-12-13
Tomorrow: 2024-12-14


In [46]:
# i) Find indices of non-zero elements from [1,2,0,0,4,0]. In all the above questions explain your
#    approach.

In [48]:
array = np.array([1, 2, 0, 0, 4, 0])

non_zero_indices = np.nonzero(array)

print(non_zero_indices)

(array([0, 1, 4]),)


In [ ]:
# # number four i used intro_numpy notebook,mathematics foundations for data science notes pdf,linear algebra for data science Plus some little knowledge of mathematical c